# Generated by Django 2.1.7 on 2019-06-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='thumbnail',
            field=models.FileField(default='no-image.png', upload_to=''),
        ),
    ]
